import { env } from "../shared/config/env.js";

export const IKIRU_CONFIG = {
  BASE_URL: env.IKIRU_BASE_URL,
  MAX_RETRIES: env.IKIRU_MAX_RETRIES,
  RETRY_DELAY: env.IKIRU_RETRY_DELAY,
  TOTAL_TIMEOUT: env.IKIRU_TOTAL_TIMEOUT,
  REQUEST_TIMEOUT: env.IKIRU_REQUEST_TIMEOUT,
  MAX_PAGES: env.IKIRU_MAX_PAGES,
  MAX_CHAPTERS: env.IKIRU_MAX_CHAPTERS,
  CHAPTER_LIST_MAX_PAGES: env.IKIRU_CHAPTER_LIST_MAX_PAGES,
  EMPTY_PAGE_BREAK_STREAK: 1,
};

export const SECONDARY_CONFIG = {
  API_BASE: env.SHINIGAMI_API_BASE,
  MAX_RETRIES: env.SHINIGAMI_MAX_RETRIES,
  RETRY_DELAY: env.SHINIGAMI_RETRY_DELAY,
  TIMEOUT: env.SHINIGAMI_TIMEOUT,
  REQUEST_TIMEOUT: env.SECONDARY_REQUEST_TIMEOUT,
  TOTAL_TIMEOUT: env.SECONDARY_TOTAL_TIMEOUT,
  LOOKBACK_HOURS: env.SHINIGAMI_LOOKBACK_HOURS,
  DIRECT_FALLBACK_MAX_URLS: env.SHINIGAMI_DIRECT_FALLBACK_MAX_URLS,
  DETAIL_MAX_MANGA: env.SHINIGAMI_DETAIL_MAX_MANGA,
  CHAPTER_LIST_MAX_PAGES: env.SHINIGAMI_CHAPTER_LIST_MAX_PAGES,
  MAX_ROWS: env.SHINIGAMI_MAX_ROWS || 20,
  MAX_CONCURRENCY: env.SHINIGAMI_MAX_CONCURRENCY || 5,
  MAX_EXPANSION_SEARCHES: env.SHINIGAMI_MAX_EXPANSION_SEARCHES || 5,
};
